function getPhoneCountryCodes(){
    var vals = [
        {name:'United Kingdom',code:'44'},
        {name:'Ireland',code:'353'},
        {name:'Afghanistan',code:'93'},
        {name:'Albania',code:'355'},
        {name:'Algeria',code:'213'},
        {name:'Andorra',code:'376'},
        {name:'Angola',code:'244'},
        {name:'Antigua and Barbuda',code:'1-268'},
        {name:'Argentina',code:'54'},
        {name:'Armenia',code:'374'},
        {name:'Australia',code:'61'},
        {name:'Austria',code:'43'},
        {name:'Azerbaijan',code:'994'},
        {name:'Bahamas, The',code:'1-242'},
        {name:'Bahrain',code:'973'},
        {name:'Bangladesh',code:'880'},
        {name:'Barbados',code:'1-246'},
        {name:'Belarus',code:'375'},
        {name:'Belgium',code:'32'},
        {name:'Belize',code:'501'},
        {name:'Benin',code:'229'},
        {name:'Bhutan',code:'975'},
        {name:'Bolivia',code:'591'},
        {name:'Bosnia and Herzegovina',code:'387'},
        {name:'Botswana',code:'267'},
        {name:'Brazil',code:'55'},
        {name:'Brunei',code:'673'},
        {name:'Bulgaria',code:'359'},
        {name:'Burkina Faso',code:'226'},
        {name:'Burundi',code:'257'},
        {name:'Cambodia',code:'855'},
        {name:'Cameroon',code:'237'},
        {name:'Canada',code:'1'},
        {name:'Cape Verde',code:'238'},
        {name:'Central African Republic',code:'236'},
        {name:'Chad',code:'235'},
        {name:'Chile',code:'56'},
        {name:'China, People\'s Republic of',code:'86'},
        {name:'Colombia',code:'57'},
        {name:'Comoros',code:'269'},
        {name:'Congo, Democratic Republic of the (Congo – Kinshasa)',code:'243'},
        {name:'Congo, Republic of the (Congo – Brazzaville)',code:'242'},
        {name:'Costa Rica',code:'506'},
        {name:'Cote d\'Ivoire (Ivory Coast)',code:'225'},
        {name:'Croatia',code:'385'},
        {name:'Cuba',code:'53'},
        {name:'Cyprus',code:'357'},
        {name:'Czech Republic',code:'420'},
        {name:'Denmark',code:'45'},
        {name:'Djibouti',code:'253'},
        {name:'Dominica',code:'1-767'},
        {name:'Dominican Republic',code:'1-809'},
        {name:'Ecuador',code:'593'},
        {name:'Egypt',code:'20'},
        {name:'El Salvador',code:'503'},
        {name:'Equatorial Guinea',code:'240'},
        {name:'Eritrea',code:'291'},
        {name:'Estonia',code:'372'},
        {name:'Ethiopia',code:'251'},
        {name:'Fiji',code:'679'},
        {name:'Finland',code:'358'},
        {name:'France',code:'33'},
        {name:'Gabon',code:'241'},
        {name:'Gambia, The',code:'220'},
        {name:'Georgia',code:'995'},
        {name:'Germany',code:'49'},
        {name:'Ghana',code:'233'},
        {name:'Greece',code:'30'},
        {name:'Grenada',code:'1-473'},
        {name:'Guatemala',code:'502'},
        {name:'Guinea',code:'224'},
        {name:'Guinea-Bissau',code:'245'},
        {name:'Guyana',code:'592'},
        {name:'Haiti',code:'509'},
        {name:'Honduras',code:'504'},
        {name:'Hungary',code:'36'},
        {name:'Iceland',code:'354'},
        {name:'India',code:'91'},
        {name:'Indonesia',code:'62'},
        {name:'Iran',code:'98'},
        {name:'Iraq',code:'964'},

        {name:'Israel',code:'972'},
        {name:'Italy',code:'39'},
        {name:'Jamaica',code:'1-876'},
        {name:'Japan',code:'81'},
        {name:'Jordan',code:'962'},
        {name:'Kazakhstan',code:'7'},
        {name:'Kenya',code:'254'},
        {name:'Kiribati',code:'686'},
        {name:'Korea, Democratic People\'s Republic of (North Korea)',code:'850'},
        {name:'Korea, Republic of (South Korea)',code:'82'},
        {name:'Kuwait',code:'965'},
        {name:'Kyrgyzstan',code:'996'},
        {name:'Laos',code:'856'},
        {name:'Latvia',code:'371'},
        {name:'Lebanon',code:'961'},
        {name:'Lesotho',code:'266'},
        {name:'Liberia',code:'231'},
        {name:'Libya',code:'218'},
        {name:'Liechtenstein',code:'423'},
        {name:'Lithuania',code:'370'},
        {name:'Luxembourg',code:'352'},
        {name:'Macedonia',code:'389'},
        {name:'Madagascar',code:'261'},
        {name:'Malawi',code:'265'},
        {name:'Malaysia',code:'60'},
        {name:'Maldives',code:'960'},
        {name:'Mali',code:'223'},
        {name:'Malta',code:'356'},
        {name:'Marshall Islands',code:'692'},
        {name:'Mauritania',code:'222'},
        {name:'Mauritius',code:'230'},
        {name:'Mexico',code:'52'},
        {name:'Micronesia',code:'691'},
        {name:'Moldova',code:'373'},
        {name:'Monaco',code:'377'},
        {name:'Mongolia',code:'976'},
        {name:'Montenegro',code:'382'},
        {name:'Morocco',code:'212'},
        {name:'Mozambique',code:'258'},
        {name:'Myanmar (Burma)',code:'95'},
        {name:'Namibia',code:'264'},
        {name:'Nauru',code:'674'},
        {name:'Nepal',code:'977'},
        {name:'Netherlands',code:'31'},
        {name:'New Zealand',code:'64'},
        {name:'Nicaragua',code:'505'},
        {name:'Niger',code:'227'},
        {name:'Nigeria',code:'234'},
        {name:'Norway',code:'47'},
        {name:'Oman',code:'968'},
        {name:'Pakistan',code:'92'},
        {name:'Palau',code:'680'},
        {name:'Panama',code:'507'},
        {name:'Papua New Guinea',code:'675'},
        {name:'Paraguay',code:'595'},
        {name:'Peru',code:'51'},
        {name:'Philippines',code:'63'},
        {name:'Poland',code:'48'},
        {name:'Portugal',code:'351'},
        {name:'Qatar',code:'974'},
        {name:'Romania',code:'40'},
        {name:'Russia',code:'7'},
        {name:'Rwanda',code:'250'},
        {name:'Saint Kitts and Nevis',code:'1-869'},
        {name:'Saint Lucia',code:'1-758'},
        {name:'Saint Vincent and the Grenadines',code:'1-784'},
        {name:'Samoa',code:'685'},
        {name:'San Marino',code:'378'},
        {name:'Sao Tome and Principe',code:'239'},
        {name:'Saudi Arabia',code:'966'},
        {name:'Senegal',code:'221'},
        {name:'Serbia',code:'381'},
        {name:'Seychelles',code:'248'},
        {name:'Sierra Leone',code:'232'},
        {name:'Singapore',code:'65'},
        {name:'Slovakia',code:'421'},
        {name:'Slovenia',code:'386'},
        {name:'Solomon Islands',code:'677'},
        {name:'Somalia',code:'252'},
        {name:'South Africa',code:'27'},
        {name:'Spain',code:'34'},
        {name:'Sri Lanka',code:'94'},
        {name:'Sudan',code:'249'},
        {name:'Suriname',code:'597'},
        {name:'Swaziland',code:'268'},
        {name:'Sweden',code:'46'},
        {name:'Switzerland',code:'41'},
        {name:'Syria',code:'963'},
        {name:'Tajikistan',code:'992'},
        {name:'Tanzania',code:'255'},
        {name:'Thailand',code:'66'},
        {name:'Timor-Leste (East Timor)',code:'670'},
        {name:'Togo',code:'228'},
        {name:'Tonga',code:'676'},
        {name:'Trinidad and Tobago',code:'1-868'},
        {name:'Tunisia',code:'216'},
        {name:'Turkey',code:'90'},
        {name:'Turkmenistan',code:'993'},
        {name:'Tuvalu',code:'688'},
        {name:'Uganda',code:'256'},
        {name:'Ukraine',code:'380'},
        {name:'United Arab Emirates',code:'971'},

        {name:'United States',code:'1'},
        {name:'Uruguay',code:'598'},
        {name:'Uzbekistan',code:'998'},
        {name:'Vanuatu',code:'678'},
        {name:'Vatican City',code:'379'},
        {name:'Venezuela',code:'58'},
        {name:'Vietnam',code:'84'},
        {name:'Yemen',code:'967'},
        {name:'Zambia',code:'260'},
        {name:'Zimbabwe',code:'263'}
    ];
    return vals;
}
function getCountries(){
    var vals = [
        {label:'United Kingdom',val:'GBR United Kingdom'},
        {label:'Ireland',val:'IRL Ireland'},
        {label:'Afghanistan',val:'AFG Afghanistan'},
        {label:'Albania',val:'ALB Albania'},
        {label:'Algeria',val:'DZA Algeria'},
        {label:'American Samoa',val:'ASM American Samoa'},
        {label:'Andorra',val:'AND Andorra'},
        {label:'Angola',val:'AGO Angola'},
        {label:'Anguilla',val:'AIA Anguilla'},
        {label:'Antarctica',val:'ATA Antarctica'},
        {label:'Antigua and Barbuda',val:'ATG Antigua and Barbuda'},
        {label:'Argentina',val:'ARG Argentina'},
        {label:'Armenia',val:'ARM Armenia'},
        {label:'Aruba',val:'ABW Aruba'},
        {label:'Australia',val:'AUS Australia'},
        {label:'Austria',val:'AUT Austria'},
        {label:'Azerbaijan',val:'AZE Azerbaijan'},
        {label:'Bahamas',val:'BHS Bahamas'},
        {label:'Bahrain',val:'BHR Bahrain'},
        {label:'Bangladesh',val:'BGD Bangladesh'},
        {label:'Barbados',val:'BRB Barbados'},
        {label:'Belarus',val:'BLR Belarus'},
        {label:'Belgium',val:'BEL Belgium'},
        {label:'Belize',val:'BLZ Belize'},
        {label:'Benin',val:'BEN Benin'},
        {label:'Bermuda',val:'BMU Bermuda'},
        {label:'Bhutan',val:'BTN Bhutan'},
        {label:'Bolivia',val:'BOL Bolivia'},
        {label:'Bosnia and Herzegovina',val:'BIH Bosnia and Herzegovina'},
        {label:'Botswana',val:'BWA Botswana'},
        {label:'Bouvet Island',val:'BVT Bouvet Island'},
        {label:'Brazil',val:'BRA Brazil'},
        {label:'British Indian Ocean Territory',val:'IOT British Indian Ocean Territory'},
        {label:'Brunei Darussalam',val:'BRN Brunei Darussalam'},
        {label:'Bulgaria',val:'BGR Bulgaria'},
        {label:'Burkina Faso',val:'BFA Burkina Faso'},
        {label:'Burundi',val:'BDI Burundi'},
        {label:'Cambodia',val:'KHM Cambodia'},
        {label:'Cameroon',val:'CMR Cameroon'},
        {label:'Canada',val:'CAN Canada'},
        {label:'Cape Verde',val:'CPV Cape Verde'},
        {label:'Cayman Islands',val:'CYM Cayman Islands'},
        {label:'Central African Republic',val:'CAF Central African Republic'},
        {label:'Chad',val:'TCD Chad'},
        {label:'Chile',val:'CHL Chile'},
        {label:'China',val:'CHN China'},
        {label:'Christmas Island',val:'CXR Christmas Island'},
        {label:'Cocos (Keeling) Islands',val:'CCK Cocos (Keeling) Islands'},
        {label:'Colombia',val:'COL Colombia'},
        {label:'Comoros',val:'COM Comoros'},
        {label:'Congo',val:'COG Congo'},
        {label:'Cook Islands',val:'COK Cook Islands'},
        {label:'Costa Rica',val:'CRI Costa Rica'},
        {label:'Cote dIvoire',val:'CIV Cote dIvoire'},
        {label:'Croatia (local name: Hrvatska)',val:'HRV Croatia (local name: Hrvatska)'},
        {label:'Cuba',val:'CUB Cuba'},
        {label:'CYP Cyprus',val:'CYP Cyprus'},
        {label:'Czech Republic',val:'CZE Czech Republic'},
        {label:'Denmark',val:'DNK Denmark'},
        {label:'Djibouti',val:'DJI Djibouti'},
        {label:'Dominica',val:'DMA Dominica'},
        {label:'Dominican Republic',val:'DOM Dominican Republic'},
        {label:'East Timor',val:'TMP East Timor'},
        {label:'Ecuador',val:'ECU Ecuador'},
        {label:'Egypt',val:'EGY Egypt'},
        {label:'El Salvador',val:'SLV El Salvador'},
        {label:'Equatorial Guinea',val:'GNQ Equatorial Guinea'},
        {label:'Eritrea',val:'ERI Eritrea'},
        {label:'Estonia',val:'EST Estonia'},
        {label:'Ethiopia',val:'ETH Ethiopia'},
        {label:'Falkland Islands (Malvinas)',val:'FLK Falkland Islands (Malvinas)'},
        {label:'Faroe Islands',val:'FRO Faroe Islands'},
        {label:'Fiji',val:'FJI Fiji'},
        {label:'Finland',val:'FIN Finland'},
        {label:'France',val:'FRA France'},
        {label:'French Guiana',val:'GUF French Guiana'},
        {label:'French Polynesia',val:'PYF French Polynesia'},
        {label:'French Southern Territories',val:'ATF French Southern Territories'},
        {label:'Gabon',val:'GAB Gabon'},
        {label:'Gambia',val:'GMB Gambia'},
        {label:'Georgia',val:'GEO Georgia'},
        {label:'Germany',val:'D Germany'},
        {label:'Ghana',val:'GHA Ghana'},
        {label:'Gibraltar',val:'GIB Gibraltar'},
        {label:'Greece',val:'GRC Greece'},
        {label:'Greenland',val:'GRL Greenland'},
        {label:'Grenada',val:'GRD Grenada'},
        {label:'Guadeloupe',val:'GLP Guadeloupe'},
        {label:'Guam',val:'GUM Guam'},
        {label:'Guatemala',val:'GTM Guatemala'},
        {label:'Guinea',val:'GIN Guinea'},
        {label:'Guinea-Bissau',val:'GNB Guinea-Bissau'},
        {label:'Guyana',val:'GUY Guyana'},
        {label:'Haiti',val:'HTI Haiti'},
        {label:'Heard and McDonald Islands',val:'HMD Heard and McDonald Islands'},
        {label:'Honduras',val:'HND Honduras'},
        {label:'Hong Kong',val:'HKG Hong Kong'},
        {label:'Hungary',val:'HUN Hungary'},
        {label:'Iceland',val:'ISL Iceland'},
        {label:'India',val:'IND India'},
        {label:'Indonesia',val:'IDN Indonesia'},
        {label:'Iran (Islamic Republic of)',val:'IRN Iran (Islamic Republic of)'},
        {label:'Iraq',val:'IRQ Iraq'},
        {label:'Israel',val:'ISR Israel'},
        {label:'Italy',val:'ITA Italy'},
        {label:'Jamaica',val:'JAM Jamaica'},
        {label:'Japan',val:'JPN Japan'},
        {label:'Jordan',val:'JOR Jordan'},
        {label:'Kazakhstan',val:'KAZ Kazakhstan'},
        {label:'Kenya',val:'KEN Kenya'},
        {label:'Kiribati',val:'KIR Kiribati'},
        {label:'Korea, Democratic Peoples Republic of',val:'PRK Korea, Democratic Peoples Republic of'},
        {label:'Korea, Republic of',val:'KOR Korea, Republic of'},
        {label:'Kuwait',val:'KWT Kuwait'},
        {label:'Kyrgyzstan',val:'KGZ Kyrgyzstan'},
        {label:'Lao Peoples',val:'LAO Lao Peoples'},
        {label:'Latvia',val:'LVA Latvia'},
        {label:'Lebanon',val:'LBN Lebanon'},
        {label:'Lesotho',val:'LSO Lesotho'},
        {label:'Liberia',val:'LBR Liberia'},
        {label:'Libyan Arab Jamahiriya',val:'LBY Libyan Arab Jamahiriya'},
        {label:'Liechtenstein',val:'LIE Liechtenstein'},
        {label:'Lithuania',val:'LTU Lithuania'},
        {label:'Luxembourg',val:'LUX Luxembourg'},
        {label:'Macau',val:'MAC Macau'},
        {label:'Macedonia, Former Yugoslav Republic of',val:'MKD Macedonia, Former Yugoslav Republic of'},
        {label:'Madagascar',val:'MDG Madagascar'},
        {label:'Malawi',val:'MWI Malawi'},
        {label:'Malaysia',val:'MYS Malaysia'},
        {label:'Maldives',val:'MDV Maldives'},
        {label:'Mali',val:'MLI Mali'},
        {label:'Malta',val:'MLT Malta'},
        {label:'Marshall Islands',val:'MHL Marshall Islands'},
        {label:'Martinique',val:'MTQ Martinique'},
        {label:'Mauritania',val:'MRT Mauritania'},
        {label:'Mauritius',val:'MUS Mauritius'},
        {label:'Mayotte',val:'MYT Mayotte'},
        {label:'Mexico',val:'MEX Mexico'},
        {label:'Micronesia, Federated States Of',val:'FSM Micronesia, Federated States Of'},
        {label:'Moldova, Republic of',val:'MDA Moldova, Republic of'},
        {label:'Monaco',val:'MCO Monaco'},
        {label:'Mongolia',val:'MNG Mongolia'},
        {label:'Montserrat',val:'MSR Montserrat'},
        {label:'Morocco',val:'MAR Morocco'},
        {label:'Mozambique',val:'MOZ Mozambique'},
        {label:'Myanmar',val:'MMR Myanmar'},
        {label:'Namibia',val:'NAM Namibia'},
        {label:'Nauru',val:'NRU Nauru'},
        {label:'Nepal',val:'NPL Nepal'},
        {label:'Netherlands',val:'NLD Netherlands'},
        {label:'Netherlands Antilles',val:'ANT Netherlands Antilles'},
        {label:'New Caledonia',val:'NCL New Caledonia'},
        {label:'New Zealand',val:'NZL New Zealand'},
        {label:'Nicaragua',val:'NIC Nicaragua'},
        {label:'Niger',val:'NER Niger'},
        {label:'Nigeria',val:'NGA Nigeria'},
        {label:'Niue',val:'NIU Niue'},
        {label:'Norfolk Island',val:'NFK Norfolk Island'},
        {label:'Northern Mariana Islands',val:'MNP Northern Mariana Islands'},
        {label:'Norway',val:'NOR Norway'},
        {label:'Oman',val:'OMN Oman'},
        {label:'Pakistan',val:'PAK Pakistan'},
        {label:'Palau',val:'PLW Palau'},
        {label:'Panama',val:'PAN Panama'},
        {label:'Papua New Guinea',val:'PNG Papua New Guinea'},
        {label:'Paraguay',val:'PRY Paraguay'},
        {label:'Peru',val:'PER Peru'},
        {label:'Philippines',val:'PHL Philippines'},
        {label:'Pitcairn',val:'PCN Pitcairn'},
        {label:'Poland',val:'POL Poland'},
        {label:'Portugal',val:'PRT Portugal'},
        {label:'Puerto Rico',val:'PRI Puerto Rico'},
        {label:'Qatar',val:'QAT Qatar'},
        {label:'Reunion',val:'REU Reunion'},
        {label:'Romania',val:'ROM Romania'},
        {label:'Russian Federation',val:'RUS Russian Federation'},
        {label:'Rwanda',val:'RWA Rwanda'},
        {label:'St. Helena',val:'SHN St. Helena'},
        {label:'Saint Kitts and Nevis',val:'KNA Saint Kitts and Nevis'},
        {label:'Saint Lucia',val:'LCA Saint Lucia'},
        {label:'St. Pierre and Miquelon',val:'SPM St. Pierre and Miquelon'},
        {label:'Saint Vincent and the Grenadines',val:'VCT Saint Vincent and the Grenadines'},
        {label:'Samoa',val:'WSM Samoa'},
        {label:'San Marino',val:'SMR San Marino'},
        {label:'Sao Tome and Principe',val:'STP Sao Tome and Principe'},
        {label:'Saudi Arabia',val:'SAU Saudi Arabia'},
        {label:'Senegal',val:'SEN Senegal'},
        {label:'Seychelles',val:'SYC Seychelles'},
        {label:'Sierra Leone',val:'SLE Sierra Leone'},
        {label:'Singapore',val:'SGP Singapore'},
        {label:'Slovakia (Slovak Republic)',val:'SVK Slovakia (Slovak Republic)'},
        {label:'Slovenia',val:'SVN Slovenia'},
        {label:'Solomon Islands',val:'SLB Solomon Islands'},
        {label:'Somalia',val:'SOM Somalia'},
        {label:'South Africa',val:'ZAF South Africa'},
        {label:'South Georgia &amp; South Sandwich Islands',val:'SGS South Georgia &amp; South Sandwich Islands'},
        {label:'Spain',val:'ESP Spain'},
        {label:'Sri Lanka',val:'LKA Sri Lanka'},
        {label:'Sudan',val:'SDN Sudan'},
        {label:'Suriname',val:'SUR Suriname'},
        {label:'Svalbard and Jan Mayen Islands',val:'SJM Svalbard and Jan Mayen Islands'},
        {label:'Swaziland',val:'SWZ Swaziland'},
        {label:'Sweden',val:'SWE Sweden'},
        {label:'Switzerland',val:'CHE Switzerland'},
        {label:'Syrian Arab Republic',val:'SYR Syrian Arab Republic'},
        {label:'Taiwan',val:'TWN Taiwan'},
        {label:'Tajikistan',val:'TJK Tajikistan'},
        {label:'Tanzania, United Republic of',val:'TZA Tanzania, United Republic of'},
        {label:'Thailand',val:'THA Thailand'},
        {label:'Togo',val:'TGO Togo'},
        {label:'Tokelau',val:'TKL Tokelau'},
        {label:'Tonga',val:'TON Tonga'},
        {label:'Trinidad and Tobago',val:'TTO Trinidad and Tobago'},
        {label:'Tunisia',val:'TUN Tunisia'},
        {label:'Turkey',val:'TUR Turkey'},
        {label:'Turkmenistan',val:'TKM Turkmenistan'},
        {label:'Turks and Caicos Islands',val:'TCA Turks and Caicos Islands'},
        {label:'Tuvalu',val:'TUV Tuvalu'},
        {label:'Uganda',val:'UGA Uganda'},
        {label:'Ukraine',val:'UKR Ukraine'},
        {label:'United Arab Emirates',val:'ARE United Arab Emirates'},
        {label:'United States of America',val:'USA United States of America'},
        {label:'United States Minor Outlying Islands',val:'UMI United States Minor Outlying Islands'},
        {label:'Uruguay',val:'URY Uruguay'},
        {label:'Uzbekistan',val:'UZB Uzbekistan'},
        {label:'Vanuatu',val:'VUT Vanuatu'},
        {label:'Vatican City State (Holy See)',val:'VAT Vatican City State (Holy See)'},
        {label:'Venezuela',val:'VEN Venezuela'},
        {label:'Vietnam',val:'VNM Vietnam'},
        {label:'Virgin Islands (British)',val:'VGB Virgin Islands (British)'},
        {label:'Virgin Islands (U.S.)',val:'VIR Virgin Islands (U.S.)'},
        {label:'Wallis and Futuna Islands',val:'WLF Wallis and Futuna Islands'},
        {label:'Western Sahara',val:'ESH Western Sahara'},
        {label:'Yemen',val:'YEM Yemen'},
        {label:'Yugoslavia',val:'YUG Yugoslavia'},
        {label:'Zaire',val:'ZAR Zaire'},
        {label:'Zambia',val:'ZMB Zambia'},
        {label:'Zimbabwe',val:'ZWE Zimbabwe'}
    ];
    return vals;
}
function getNationalities(){
    var vals = [
        {code:'GB UK - British Citizen',name:'GB UK - British Citizen'},
        {code:'GB UK - British National (Overseas)',name:'GB UK - British National (Overseas)'},
        {code:'IE Ireland',name:'Ireland'},
        {code:'AD Andorra',name:'Andorra'},
        {code:'AT Austria',name:'Austria'},
        {code:'BE Belgium',name:'Belgium'},
        {code:'BN Brunei',name:'Brunei'},
        {code:'CA Canada',name:'Canada'},
        {code:'DK Denmark',name:'Denmark'},
        {code:'FI Finland',name:'Finland'},
        {code:'FR France',name:'France'},
        {code:'DE Germany',name:'Germany'},
        {code:'GR Greece',name:'Greece'},
        {code:'HK Hong Kong SAR (not BN(O))',name:'Hong Kong SAR (not BN(O))'},
        {code:'IS Iceland',name:'Iceland'},
        {code:'IT Italy',name:'Italy'},
        {code:'JP Japan',name:'Japan'},
        {code:'LI Liechtenstein',name:'Liechtenstein'},
        {code:'LU Luxembourg',name:'Luxembourg'},
        {code:'MY Malaysia',name:'Malaysia'},
        {code:'MT Malta',name:'Malta'},
        {code:'MC Monaco',name:'Monaco'},
        {code:'NL The Netherlands',name:'The Netherlands'},
        {code:'NO Norway',name:'Norway'},
        {code:'PT Portugal',name:'Portugal'},
        {code:'SG Singapore',name:'Singapore'},
        {code:'KR South Korea',name:'South Korea'},
        {code:'ES Spain',name:'Spain'},
        {code:'SE Sweden',name:'Sweden'},
        {code:'CH Switzerland',name:'Switzerland'},
        {code:'TW Taiwan',name:'Taiwan'},
        {code:'US USA',name:'USA'},
        {code:'VA Vatican City',name:'Vatican City'}
    ];
    return vals;
}
function getYearsLast( num ){
    var dat = new Date();
    var yyyy = dat.getFullYear();
    var vals = [];
    for( var i=0; i<num; i++){
        var yy = yyyy - i;
        vals.push( {val:""+yy,label:""+yy} );
    };
    return vals;
}
function getYearsNext( num ){
    var dat = new Date();
    var yyyy = dat.getFullYear();
    var vals = [];
    for( var i=0; i<num; i++){
        var yy = yyyy + i;
        vals.push( {val:""+yy,label:""+yy} );
    };
    return vals;
}
function getMonths(){
    var vals = [
        {label:"January",val:'JAN'},
        {label:"February",val:'FEB'},
        {label:"March",val:'MAR'},
        {label:"April",val:'APR'},
        {label:"May",val:'MAY'},
        {label:"June",val:'JUN'},
        {label:"July",val:'JUL'},
        {label:"August",val:'AUG'},
        {label:"September",val:'SEP'},
        {label:"October",val:'OCT'},
        {label:"November",val:'NOV'},
        {label:"December",val:'DEC'}
    ];
    return vals;
}
function getMonthsNum(){
    var vals = [
        {label:"January",val:'01'},
        {label:"February",val:'02'},
        {label:"March",val:'03'},
        {label:"April",val:'04'},
        {label:"May",val:'05'},
        {label:"June",val:'06'},
        {label:"July",val:'07'},
        {label:"August",val:'08'},
        {label:"September",val:'09'},
        {label:"October",val:'10'},
        {label:"November",val:'11'},
        {label:"December",val:'12'}
    ];
    return vals;
}
function getMonthsNumbers(){
    var vals = [
        {label:"01",val:'01'},
        {label:"02",val:'02'},
        {label:"03",val:'03'},
        {label:"04",val:'04'},
        {label:"05",val:'05'},
        {label:"06",val:'06'},
        {label:"07",val:'07'},
        {label:"08",val:'08'},
        {label:"09",val:'09'},
        {label:"10",val:'10'},
        {label:"11",val:'11'},
        {label:"12",val:'12'}
    ];
    return vals;
}
function getMonthDays( max ){
    var vals = [];
    var pad = "";
    for( var i=1; i<=max; i++){
        pad = "0" + i.toString();
        pad = pad.substr(pad.length - 2);
        vals.push( {val:""+ i.toString(),label:""+ pad} );
    };
    return vals;
}

function pad( str, len ){
    // pad out the passed string to "len" characters.
    var pad = "0" + str;
    pad = pad.substr(pad.length - len);
    return pad
}